# Generated by Django 3.1.6 on 2025-03-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=34)),
                ('coursename', models.CharField(max_length=34)),
                ('duration', models.CharField(max_length=34)),
                ('fees', models.IntegerField()),
                ('coursedetail', models.CharField(max_length=100)),
            ],
        ),
    ]
