# Generated by Django 3.1.6 on 2025-03-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('courseid', models.CharField(max_length=50)),
                ('batchtitle', models.CharField(max_length=50)),
                ('startdate', models.CharField(max_length=20)),
                ('instname', models.CharField(max_length=40)),
            ],
        ),
    ]
