# Generated by Django 3.1.6 on 2025-03-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='sno',
            new_name='batchid',
        ),
        migrations.AddField(
            model_name='batch',
            name='batchstatus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='batch',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.course'),
        ),
    ]
