# Generated by Django 3.1.6 on 2025-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20250307_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batchtime',
            field=models.CharField(default=8, max_length=10),
            preserve_default=False,
        ),
    ]
