# Generated by Django 3.1.6 on 2025-03-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_batch_batchtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventimage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
