# Generated by Django 3.1.6 on 2025-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mstuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fnm', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('mno', models.CharField(max_length=10, unique=True)),
                ('dob', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
