# Generated by Django 3.1.6 on 2025-03-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstuser',
            name='role',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
    ]
