# Generated by Django 3.1.6 on 2025-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my1', '0002_mstuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstuser',
            name='image',
            field=models.FileField(default=2, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
