# Generated by Django 3.1.6 on 2025-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my1', '0003_mstuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mno', models.CharField(max_length=13)),
                ('subject', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
