# Generated by Django 3.1.6 on 2025-03-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selectbatch',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('batchid', models.BigIntegerField()),
                ('batchtitle', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('batchtime', models.CharField(max_length=20)),
                ('instname', models.CharField(max_length=50)),
            ],
        ),
    ]
