# Generated by Django 3.1.6 on 2025-03-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20250313_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('batchid', models.IntegerField()),
                ('admissionno', models.AutoField(primary_key=True, serialize=False)),
                ('admissiondate', models.DateField()),
                ('emailid', models.CharField(max_length=50)),
            ],
        ),
    ]
